### ISSUE TITLE
Can this work also with JS/Dynamic templates

### ISSUE THREAD

**Issue by zemiak** [sammyd/StandaloneTVML#1]
Hello,

I would like to see this working with dynamic templates, like SomeTemplate.xml.js from tvOS Apple Templates and plain JS files (for loading with evaluateScripts). Is it possible to achieve it?

**Comment by sammyd** [comment]
I've used this successfully with a JavaScript templating engine - so the TVML files are static and contain templating tags which are replaced at runtime by the engine. I don't really think the "entire TVML document as a string in a JS file" is a very scalable solution. That's not how HTML is generated, for example.

Alternatively you could update the JavaScript resource loader to run the retrieved string through `eval()`.

Yet another option would be to build something more complex with JavaScript Core that made use of the `evalutateScripts` function, but that doesn't sound that straight forward.

**Comment by zemiak** [comment]
First of all, thanks for your answer! Performace is not a problem in my case, so eval() is a viable option (soon to be replaced with Mustache.js in my project, anyway).

And your eval() answer is bringing me to another option with JS:
1. load the JS file via var resource = resourceLoader.loadBundleResource("SomeFile.js")
2. eval(resource)

Am I thinking in the right direction (let's put the performance question away for a while)?

Thanks!

**Comment by sammyd** [comment]
Mustache.js is exactly the approach that I settled on to use for the TVML-based chapters of the upcoming raywenderlich.com book "tvOS Apprentice". This approach seems to work pretty well, and separates the data from the layout in a way that you'd expect.

And yes, your `eval()` solution looks exactly like I was imagining. I think it should work reasonably well.

**Comment by zemiak** [comment]
Thank you very much!

**Comment by zemiak** [comment]
Hello,

I have been thinking about locally providing Javascript Files (mentioned in previous posts) and also images and/or other media/non-media files referenced in TVML templates.

See https://gist.github.com/zemiak/86d3964131672a7bc382 -- mainly resourceLoader.getLocalUrl (it is, of course, not polished now in the gist). It works in the emulator, I'm waiting for a cable to test it on an actual device.

It seems to me as a better solution, because no content is loaded into memory in the Swift code and transferred back to the JS code. Without it, every image would have to be:
1. loaded into memory
2. encoded as Base64 (btoa())
3. inserted as a "data" image into the template

I would appreciate any comment you may have, and, please, feel free to use the code as you wish.

**Comment by sammyd** [comment]
@zemiak I have written almost exactly the same code in the projects I've created for http://www.raywenderlich.com/store/tvos-apprentice ;)

There is one alternative for loading binary resources, and that's via TVMLKit. You can add your own custom resources to the `resource://` URL scheme using `TVInterfaceFactory`.

However, for the general case I used the resource loader approach, by adding the URL method as you indicated here.

I imagine that we'll make the code available for some of these projects at some point, but I think it'll have to wait until after the publication of the book :/
